name: Continuous Integration and Delivery

on: [push]

env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/lafton-album

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true

      - name: Build image
        run: |
          docker build --cache-from ${{ env.IMAGE }}:latest \
          --tag ${{ env.IMAGE }}:latest \
          --file Dockerfile \
          "."

      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest
